"""Initial migration

Revision ID: d80d492fd489
Revises: 
Create Date: 2026-05-22 21:50:18.314283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80d492fd489'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('tmdb_genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=255), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_genre_id')
    )
    op.create_table('images',
    sa.Column('file_path', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('poster', 'backdrop', 'logo', name='imagetype'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('iso_3166_1', sa.String(length=5), nullable=True),
    sa.Column('iso_639_1', sa.String(length=5), nullable=True),
    sa.Column('vote_average', sa.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('file_path')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.String(length=128), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tmdb_collections',
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=False),
    sa.Column('name_original', sa.String(length=255), nullable=False),
    sa.Column('original_language', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_collection_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('titles',
    sa.Column('title_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=10), nullable=True),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=True),
    sa.Column('jellyfin_id', sa.String(length=32), nullable=True),
    sa.Column('title_type', sa.Enum('movie', 'tv', name='titletype'), nullable=False),
    sa.Column('name_original', sa.String(length=255), nullable=True),
    sa.Column('tmdb_vote_average', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('imdb_vote_average', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('imdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('movie_runtime', sa.Integer(), nullable=True),
    sa.Column('movie_revenue', sa.BigInteger(), nullable=True),
    sa.Column('movie_budget', sa.BigInteger(), nullable=True),
    sa.Column('original_language', sa.String(length=64), nullable=True),
    sa.Column('origin_country', sa.String(length=64), nullable=True),
    sa.Column('awards', sa.String(length=255), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tmdb_collection_id'], ['tmdb_collections.tmdb_collection_id'], ),
    sa.PrimaryKeyConstraint('title_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index(op.f('ix_titles_tmdb_collection_id'), 'titles', ['tmdb_collection_id'], unique=False)
    op.create_table('tmdb_collection_translations',
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=False),
    sa.Column('iso_639_1', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('default_poster_image_path', sa.String(length=64), nullable=True),
    sa.Column('default_backdrop_image_path', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['default_backdrop_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['default_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['tmdb_collection_id'], ['tmdb_collections.tmdb_collection_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_collection_id', 'iso_639_1')
    )
    op.create_table('tmdb_collection_user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=False),
    sa.Column('chosen_poster_image_path', sa.String(length=255), nullable=True),
    sa.Column('chosen_backdrop_image_path', sa.String(length=255), nullable=True),
    sa.Column('chosen_locale', sa.String(length=16), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chosen_backdrop_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['chosen_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['tmdb_collection_id'], ['tmdb_collections.tmdb_collection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tmdb_collection_id')
    )
    op.create_table('user_collections',
    sa.Column('collection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_collection_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_collection_id'], ['user_collections.collection_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['key'], ['settings.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_vote_average', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id'),
    sa.UniqueConstraint('title_id', 'season_number', name='uq_season_title_number')
    )
    op.create_table('title_age_ratings',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('iso_3166_1', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.String(length=64), nullable=True),
    sa.Column('descriptors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'iso_3166_1')
    )
    op.create_table('title_folders',
    sa.Column('title_folder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_folder_path', sa.String(length=512), nullable=False),
    sa.Column('title_folder_name', sa.String(length=256), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_folder_id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_table('title_genres',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.tmdb_genre_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'genre_id')
    )
    op.create_table('title_translations',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('iso_639_1', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('default_poster_image_path', sa.String(length=64), nullable=True),
    sa.Column('default_backdrop_image_path', sa.String(length=64), nullable=True),
    sa.Column('default_logo_image_path', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['default_backdrop_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['default_logo_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['default_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'iso_639_1')
    )
    op.create_table('title_user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('in_library', sa.Boolean(), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=True),
    sa.Column('in_watchlist', sa.Boolean(), nullable=True),
    sa.Column('watch_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('chosen_poster_image_path', sa.String(length=255), nullable=True),
    sa.Column('chosen_backdrop_image_path', sa.String(length=255), nullable=True),
    sa.Column('chosen_logo_image_path', sa.String(length=255), nullable=True),
    sa.Column('chosen_locale', sa.String(length=16), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chosen_backdrop_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['chosen_logo_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['chosen_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'title_id')
    )
    op.create_table('user_collection_titles',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['user_collections.collection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'collection_id')
    )
    op.create_table('episodes',
    sa.Column('episode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_vote_average', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('default_backdrop_image_path', sa.String(length=64), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id'),
    sa.UniqueConstraint('season_id', 'episode_number', name='uq_episode_season_number')
    )
    op.create_table('image_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=64), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('title_id IS NOT NULL OR season_id IS NOT NULL OR tmdb_collection_id IS NOT NULL', name='chk_link_has_target'),
    sa.ForeignKeyConstraint(['file_path'], ['images.file_path'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_collection_id'], ['tmdb_collections.tmdb_collection_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', 'title_id', 'season_id', 'tmdb_collection_id', name='uix_image_link_identity', postgresql_nulls_not_distinct=True)
    )
    op.create_table('season_translations',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('iso_639_1', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('default_poster_image_path', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['default_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', 'iso_639_1')
    )
    op.create_table('season_user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('chosen_poster_image_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_poster_image_path'], ['images.file_path'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'season_id')
    )
    op.create_table('episode_translations',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('iso_639_1', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'iso_639_1')
    )
    op.create_table('episode_user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.create_table('video_assets',
    sa.Column('video_asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('title_folder_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('video_type', sa.Enum('movie', 'episode', 'featurette', name='videotype'), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('hdr_type', sa.String(length=255), nullable=True),
    sa.Column('filesize_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_folder_id'], ['title_folders.title_folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_asset_id')
    )
    op.create_index(op.f('ix_video_assets_file_path'), 'video_assets', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_assets_file_path'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_table('episode_user_details')
    op.drop_table('episode_translations')
    op.drop_table('season_user_details')
    op.drop_table('season_translations')
    op.drop_table('image_links')
    op.drop_table('episodes')
    op.drop_table('user_collection_titles')
    op.drop_table('title_user_details')
    op.drop_table('title_translations')
    op.drop_table('title_genres')
    op.drop_table('title_folders')
    op.drop_table('title_age_ratings')
    op.drop_table('seasons')
    op.drop_table('user_settings')
    op.drop_table('user_collections')
    op.drop_table('tmdb_collection_user_details')
    op.drop_table('tmdb_collection_translations')
    op.drop_index(op.f('ix_titles_tmdb_collection_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tmdb_collections')
    op.drop_table('settings')
    op.drop_table('images')
    op.drop_table('genres')
    # ### end Alembic commands ###
