"""Add fuzzy search indexes

Revision ID: e974b7b983e1
Revises: 09e4e363ef72
Create Date: 2026-09-05 16:22:32.032139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e974b7b983e1'
down_revision: Union[str, Sequence[str], None] = '09e4e363ef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ensure the pg_trgm extension exists before creating the trigram index
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    
    op.create_index('idx_title_translations_name_trgm', 'title_translations', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_title_translations_name_trgm', table_name='title_translations', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
